

#user profile img
file.profile.upload.path=/Users/sankim/Documents/userprofile
file.profile.loading.path=file:/Users/sankim/Documents/userprofile/

# teacher cert img
file.cert.upload.path=/Users/sankim/Documents/cert
file.cert.loading.path=file:/Users/sankim/Documents/cert/

# album img
file.album.upload.path=c:\\album
file.album.loading.path=file:///c://album/

# user noticefile
file.noticefile.upload.path=c:\\noticefile
file.noticefile.loading.path=file:///c://noticefile/

## user profile img
#file.profile.upload.path=c:\\userprofile
#file.profile.loading.path=file:///c://userprofile/
##
## teacher cert img
#file.cert.upload.path=c:\\cert
#file.cert.loading.path=file:///c://cert/

# testBank
file.testBank.upload.path=c:\\testBank
file.testBank.loading.path=file:///c://testBank/