# album img
file.album.upload.path=urifiles/album
file.album.loading.path=file:///home/ec2-user/apache-tomcat-9.0.82/urifiles/album/

# user noticefile
file.noticefile.upload.path=urifiles/noticefile
file.noticefile.loading.path=file:///home/ec2-user/apache-tomcat-9.0.82/urifiles/noticefile/

# user profile img
file.profile.upload.path=urifiles/userprofile
file.profile.loading.path=file:///home/ec2-user/apache-tomcat-9.0.82/urifiles/userprofile/

# teacher cert img
file.cert.upload.path=urifiles/cert
file.cert.loading.path=file:///home/ec2-user/apache-tomcat-9.0.82/urifiles/cert/

# testBank
file.testBank.upload.path=urifiles/testBank
file.testBank.loading.path=file:///home/ec2-user/apache-tomcat-9.0.82/urifiles/testBank/
