#driverName=oracle.jdbc.driver.OracleDriver
#dbUrl=jdbc:oracle:thin:@192.168.0.22:1521:xe
driverName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
dbUrl=jdbc:log4jdbc:oracle:thin:@192.168.0.22:1521:xe
#dbUrl=jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
id=shoeshi
pwd=1234