#ENC
#driverName=ENC(O+54eM4TFFnxpCrRkd3y/UqGYm1lJPznxFAHMVV7k5DAsRFHR0M+p2Fi136ETZ1S)
#dbUrl=ENC(4XohooYQrb/AEcFpXhIrkNOMldmWFgu4gjdGweIwyWrqh/7AKrCo04SJqxNdRwJ2YOkfyhTSkeA=)
#id=ENC(mnnwtoPDxQYBU81P/LzLwLHugS7qptxd)
#pwd=ENC(Z6fqh+0EyL8y3XaEd2Zw8SrsOcDLuis3)
driverName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
dbUrl=jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
id=ourclass1
pwd=ourclass